name: FoodTap
main: MCPH\FoodTap\Main
version: "1.0.0"
api: [1.8.0]
author: MinecrafterPH, xFlare (original)
description: Tap any food on the ground to eat it!
website: https://github.com/MinecrafterPH/FoodTap
