name: MushRoomStewHeal
main: xFlare\MushRoomStewHeal\Loader
version: "1.5.0"
api: [1.8.0]
author: xFlare
description: Drink mushroom stew by taping it on the ground :D
website: https://github.com/xxFlare/MushRoomStewHeal
